### ISSUE TITLE
Exam task for Nikita Kolosov

### ISSUE THREAD

**Issue by YakutovDmitriy** [faramer86/BIOPYTHON_ITMO#10]
#### Main requirements

Your program should never fail.

You are free to implement the task as you want. In particular, if there are some uncertainties, you have to decide what to do.

You are free to add some functionality. Please describe all features you added.

#### Implement application `translate.py` to translate words.

You should store dictoinary in file [dict.tr](https://gist.github.com/YakutovDmitriy/3b6e2e24b7cff61380066b9c7e970e15). Note that one string can have different meanings in different languages (e.g. `Ja` is `Yes` in German and `I` in Russian). You can assume that one string can have no more than one meaning in one language.

You should assume that name of language do not depend on case: `English` is the same language as `english`.

Each word have a `popularity` - an integer from `0` to `100`. Words with the same meaning in different language have the same popularity.

---

* Add: `python translate.py + <Popularity> <Language-1> <Word-1> <Language-2> <Word-2> ...`

    Command should add list of words `<Word-1> ...` in languages `<Language-1> ...` with the same meanings with popularity `<Popularity>`.

* Translate: `python translate.py ? <From language> <To language> <Phrase>`

    Command should translate phrase `<Phrase>` from language `<From language>` to language `<To language>`. `<Phrase>` is list of several words separated by spaces: `<Word-1> ... <Word-n>`. If one of the strings from phrase is not present in language `<From language>` print a message about it. If one of the words have no translation to language `<To language>` print a message about it. Otherwise you should print translated phrase to stdout.

    Do not forget to preserve the case! For example:
    ```bash
    python translate.py ? English Russian I love you
    > Ja lublu ti
    python translate.py ? EngLiSh russian I love YOU
    > Ja lublu TI
    ```

* Translate: `python translate.py ! <To language> <Phrase>`

    Command is the same as previous one. But source language is unknown. You should choose source language and print it to the first line of output. The second line of output should contain translation of the phrase.

    Source language should be language which contain all the words from the phrase. If there is no such language, print a message about it and do not translate the phrase. If there are several suitable languages, choose one with the largest sum of popularities of words in phrase.

**Comment by faramer86** [comment]
how bad is that (translator)?

**Comment by YakutovDmitriy** [comment]
Looks good at first glance

**Comment by YakutovDmitriy** [comment]
Hello!

I found the following notes:

* Your program fails sometimes:
    * If in command `?` source language is unknown
    * If there are not enough argument to perform some operation
    * Command `+`. It fails anyway. Did you test it?

7 points

**Comment by faramer86** [comment]
"Command +. It fails anyway. Did you test it?" - it works. I just forgot add two brackets!!!

**Comment by faramer86** [comment]
6/10 - do not sounds good. Can I retake it or fix bugs or do other exercise?

**Comment by YakutovDmitriy** [comment]
This line creates variable `var` of type `tuple`:
`var = generate_variables(int(sys.argv[2]), sys.argv[3:])`
This line tries to assign new value in tuple item:
`var[5] += language.title() + ':' + word + ' '`
But tuple is immutable :(

**Comment by faramer86** [comment]
return popularity, list_with_words, languages, words, ID, string_for_file
    return [popularity, list_with_words, languages, words, ID, string_for_file]

**Comment by faramer86** [comment]
I fix that.

**Comment by YakutovDmitriy** [comment]
Hello
The following calls print nothing:
* `python translate.py + 10 English c Russian`

The following calls raise errors:
* `python translate.py ? Unknown Russian phrase`

The following calls print meaningless messages:
* `python translate.py ! German I love ti`

I can add 1 point

**Comment by faramer86** [comment]
'python translate.py + 10 English c Russian' - the following command add only first phrase ' English c ' to the dictionary and ignore second language, since it is incomplete argument. I decided that it is not complete error, that is why we can add first phrase and ignore second.
'python translate.py ? Unknown Russian phrase' - miss it
'python translate.py ! German I love ti' - The output is changed quotation of the task description. That means that in English ('Source language') there is not word 'ti' that is why we can not translate it.
